---
- name: Prepare
  hosts: localhost
  connection: local 
  tasks:
    - name: Get the netlify sites
      shell: "./node_modules/netlify-cli/bin/run sites:list | grep url | awk -F'https://' '{print $2}'"
      register: res

    - name: create netlify sites file
      template:
        src: urls.j2
        dest: urls.js
    
    
