name: Deploy

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Node install
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install JS Packages
        run: npm install

      - name: Rsync application
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -a
          path: /
          remote_path: ~/lighthouse
          remote_host: io37.ch
          remote_user: deploy
          remote_key: ${{ secrets.DEPLOY_KEY }}

      - name: Rsync crontab
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -a
          path: /
          remote_path: ~/lighthouse
          remote_host: io37.ch
          remote_user: deploy
          remote_key: ${{ secrets.DEPLOY_KEY }}
        env:
          SUDO: true
